services:
    netgen_siteaccess_routes.event_listener.request:
        class: Netgen\Bundle\SiteAccessRoutesBundle\EventListener\RequestListener
        public: true
        arguments:
            - "@netgen_siteaccess_routes.matcher"
        tags:
            - { name: kernel.event_subscriber }

    netgen_siteaccess_routes.matcher:
        class: Netgen\Bundle\SiteAccessRoutesBundle\Matcher\Matcher
        public: false
        arguments:
            - []

    netgen_siteaccess_routes.voter.default_siteaccess:
        class: Netgen\Bundle\SiteAccessRoutesBundle\Matcher\Voter\DefaultSiteAccessVoter
        public: false
        arguments:
            - "%ezpublish.siteaccess.default%"
        tags:
            - { name: netgen_siteaccess_routes.voter }

    netgen_siteaccess_routes.voter.siteaccess:
        class: Netgen\Bundle\SiteAccessRoutesBundle\Matcher\Voter\SiteAccessVoter
        public: false
        tags:
            - { name: netgen_siteaccess_routes.voter }

    netgen_siteaccess_routes.voter.siteaccess_group:
        class: Netgen\Bundle\SiteAccessRoutesBundle\Matcher\Voter\SiteAccessGroupVoter
        public: false
        arguments:
            - "%ezpublish.siteaccess.groups_by_siteaccess%"
        tags:
            - { name: netgen_siteaccess_routes.voter }
